
---
apiVersion: v1
kind: Pod
metadata:
  name: insta-pod
  labels:
    env: production
    app: instagram
spec:
  containers:
    - name: insta-cont
      image: harinath93811/dockerized-app:fb_httpd

    - name: insta-side-car-cont
      image: harinath93811/dockerized-app:fb_httpd
