apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  accessModes:
  - ReadWriteOnce  ## Only one node (machine) can read and write to this volume at a time.
  capacity:
    storage: 15Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0acc5a8a79b1449f6
   #volumeHandle: vol-0dc9d803e9e950a37