
--- 
apiVersion: v1
kind: Pod
metadata:
  name: secret-ex-pod 

spec: 
  containers:
    - name: insta-pod-cont
      image: harinath93811/dockerized-app:fb_httpd

      envFrom:
        - secretRef:
            name: mc-secret